# Generated by Django 5.0.6 on 2024-05-21 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=155)),
                ('last_name', models.CharField(max_length=155)),
            ],
            options={
                'db_table': 'AUTHOR',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
            ],
            options={
                'db_table': 'CATEGORY',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'LANGUAGE',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('year', models.DateField()),
                ('page', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='book/')),
                ('price', models.IntegerField()),
                ('author', models.ForeignKey(default='null', on_delete=django.db.models.deletion.SET_DEFAULT, to='books.author')),
                ('category', models.ForeignKey(default='null', on_delete=django.db.models.deletion.SET_DEFAULT, to='books.category')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.language')),
            ],
            options={
                'db_table': 'BOOKS',
            },
        ),
    ]
